---
- name: info de las dos VMs de Moodle
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: get VM App info
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_moo_app_name }}"
      register: detailed_vm_moo_app_info
    - name: get VM DB info
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_moo_db_name }}"
      register: detailed_vm_moo_db_info
    - name: print VM App info
      ansible.builtin.debug:
        var: detailed_vm_moo_app_info
    - name: print VM DB info
      ansible.builtin.debug:
        var: detailed_vm_moo_db_info