---
- name: Borrando dos VMs de Moodle
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
  - name: Remove a virtual machine MoodleAPP by uuid
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      uuid: "{{ vm_moo_app_uuid }}"
      state: absent
    
  - name: Remove a virtual machine MoodleDB by uuid
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      uuid: "{{ vm_moo_db_uuid }}"
      state: absent
    delegate_to: localhost